# After changing this file, check it on: https://lint.travis-ci.org/
language: python

# Python targets, as defined by https://github.com/travis-ci/travis-build/blob
# /master/spec/build/script/python_spec.rb and https://github.com/travis-ci
# /travis-build/blob/master/lib/travis/build/script/python.rb
python:
  # Standard release https://docs.travis-ci.com/user/languages
  # /python#choosing-python-versions-to-test-against
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"

  # https://docs.travis-ci.com/user/languages/python/#pypy-support
  - "pypy"
  - "pypy3"

before_install:
  # Check default Python version installed.
  - python --version

before_script:
  - pip install codecov

script:
  # Launch unittests.
  - pip install -e .[tests]
  - coverage run ./setup.py test
  - coverage report -m
  # Check coding style.
  - pycodestyle
  # Test that building packages works.
  - pip install -e .[develop]
  - ./setup.py sdist bdist_egg bdist_wheel
  # Validates package metadata.
  - ./setup.py check -m -r -s

after_script:
  - codecov
